# Generated by Django 5.0.1 on 2024-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no_filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred')], max_length=50),
        ),
    ]
